### ISSUE TITLE
Reopening the dialog with the same project selected triggers reindexing

### ISSUE THREAD

**Issue by Chris2011** [sickill/off-plugin#37] opened 2016-03-07 12:46 UTC
I know that indexing is needed but I have a project with a lot of files I open OFF, the index is working, after 5 sec (much to long I think) I can use OFF. I close it and I reopen OFF and the index runs again. It runs always after closing and reopening but I don't want to wait 5 sec again and again after reopening the dialog. There must be a better way to implement such things, maybe indexing while project selecting? and reindexing, on external changes and reindexing after adding new files etc.

**Comment by markiewb** [comment] 2016-03-07 18:48
I will fix the issue "reopening the dialog with the same project selected should not reindex"

**Comment by markiewb** [comment] 2016-03-07 22:40
Fixed in 1.3-SN https://github.com/sickill/off-plugin/commit/5b496921ab7f444428e93cc6788d4fcb220ab557

@Chris2011: Please test!

**Closed by markiewb** 2016-03-07 22:40 UTC
Labels: bug

**Comment by Chris2011** [comment] 2016-03-08 07:42
I will test it, thx for your work. Only a hint, can you pleas remember to increase the version of the plugin? I have to uninstall the 1.3 because 1.3.0.1 and 1.3.0.2 are maybe still 1.3?

**Comment by Chris2011** [comment] 2016-03-08 08:40
Ok strange, I downloaded 1.3 again, so forget my last comment ^^.

**Comment by Chris2011** [comment] 2016-03-15 15:12
Works fine, the reindexing comes up after "open OFF -> indexing is working -> close OFF -> change the project -> open OFF -> indexing is working -> close OFF -> change back to the first project, which was open in OFF -> indexing starts" I think this is the right behaviour, right?

**Comment by markiewb** [comment] 2016-03-15 20:03
@Chris2011: That is correct. If you try to search in a project, which has not been indexed, the index will be thrown away and the new project will be indexed.

**Comment by Chris2011** [comment] 2016-03-16 07:36
But the same happens, if a project is already indexed. This is correct too?

**Comment by markiewb** [comment] 2016-03-16 19:24
@Chris2011: You mean
* Select project A in the project tree
* open OFF -> Indexing is started and done
* close OFF
* open OFF -> no reindexing because it is still the same project

That is the expected behaviour

**Comment by Chris2011** [comment] 2016-03-16 20:31
No I mean:
* Select project A in the project tree
* open OFF -> Indexing is started and done
* close OFF
* Select project B in the project tree
* open OFF -> Indexing is started and done
* close OFF
* Selet project A again in the project tree
* open OFF -> Indexing is started again and done.

**Comment by markiewb** [comment] 2016-03-16 20:58
@Chris2011: That behavior is correct. Only one index exists at one point in time. The index is never persisted. It's held in memory - not very effective...
